# Generated by Django 4.2.7 on 2025-12-30 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_enhanced_fields'),
    ]

    operations = [
        # Add new fields to User
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        # Update Agent model
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='agent_photos/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        # Rename Loan customer_name to full_name and add new fields
        migrations.RenameField(
            model_name='loan',
            old_name='customer_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='loan',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='tenure_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='emi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='applicant_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('agent', 'Agent')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='has_co_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_applicant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_applicant_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='has_guarantor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('lap', 'LAP (Loan Against Property)'), ('home', 'Home Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('car', 'Car Loan'), ('other', 'Other')], max_length=50),
        ),
        # Create LoanDocument model
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pan_card', 'PAN Card'), ('aadhaar_card', 'Aadhaar Card'), ('applicant_photo', 'Applicant Photo'), ('permanent_address_proof', 'Permanent Address Proof'), ('current_address_proof', 'Current Address Proof'), ('salary_slip', 'Salary Slip'), ('bank_statement', 'Bank Statement'), ('form_16', 'Form 16'), ('service_book', 'Service Book'), ('property_documents', 'Property Documents'), ('soa_existing_loan', 'SOA of Existing Loan Account'), ('co_applicant_pan', 'Co-applicant PAN'), ('co_applicant_aadhaar', 'Co-applicant Aadhaar'), ('co_applicant_photo', 'Co-applicant Photo'), ('guarantor_pan', 'Guarantor PAN'), ('guarantor_aadhaar', 'Guarantor Aadhaar'), ('guarantor_address_proof', 'Guarantor Address Proof'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='loan_documents/%Y/%m/%d/')),
                ('is_required', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.loan')),
            ],
            options={
                'db_table': 'loan_documents',
                'unique_together': {('loan', 'document_type')},
            },
        ),
    ]
