# Generated by Django 4.2.7 on 2025-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_loan_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('government', 'Government'), ('cooperative', 'Cooperative'), ('nbfc', 'NBFC')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dsa', 'DSA'), ('employee', 'Employee'), ('agent', 'Agent')], default='employee', max_length=20),
        ),
    ]
