# Generated by Django 4.2.7 on 2026-01-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loanapplication_approval_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='follow_up_count',
            field=models.IntegerField(default=0, help_text='Number of follow-ups triggered'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='follow_up_notified_at',
            field=models.DateTimeField(blank=True, help_text='When follow-up notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='follow_up_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When follow-up was scheduled', null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('New Entry', 'New Entry'), ('Waiting for Processing', 'Waiting for Processing'), ('Required Follow-up', 'Required Follow-up'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='New Entry', max_length=50),
        ),
    ]
