# Generated by Django 4.2.7 on 2026-01-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_loanapplication_follow_up_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='action_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='follow_up_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='requires_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
