# Generated by Django 4.2.7 on 2026-01-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_loan_action_taken_at_loan_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(blank=True, help_text='Manual Agent ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Manual Employee ID', max_length=50, null=True, unique=True),
        ),
    ]
