# Generated by Django 4.2.7 on 2026-01-07 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agent_date_of_birth_agent_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Required Follow-up'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='new_entry', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_role', models.CharField(choices=[('loan_processor', 'Loan Processor'), ('verification', 'Verification Officer'), ('manager', 'Manager')], default='loan_processor', max_length=50)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('approved_loans', models.PositiveIntegerField(default=0)),
                ('rejected_loans', models.PositiveIntegerField(default=0)),
                ('total_disbursed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('assigned_loans_count', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
