# Generated by Django 4.2.7 on 2026-01-07 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_loan_status_employeeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Required Follow-up'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], max_length=50, null=True)),
                ('to_status', models.CharField(choices=[('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Required Follow-up'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_auto_triggered', models.BooleanField(default=False, help_text='True if auto-moved (e.g., follow-up)')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.loanapplication')),
            ],
            options={
                'db_table': 'loan_status_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['loan_application', '-changed_at'], name='loan_status_loan_ap_273a17_idx'), models.Index(fields=['to_status'], name='loan_status_to_stat_1a54d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('reassigned', 'Reassigned')], default='active', max_length=20)),
                ('assignment_notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_loans_history', to=settings.AUTH_USER_MODEL)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.loanapplication')),
            ],
            options={
                'db_table': 'loan_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='loan_assign_assigne_c21cc9_idx'), models.Index(fields=['loan_application'], name='loan_assign_loan_ap_e64310_idx')],
            },
        ),
    ]
