# Generated by Django 4.2.7 on 2026-01-10 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_loanstatushistory_loanassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='disbursement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Required Follow-up'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('disbursed', 'Disbursed')], default='new_entry', max_length=20),
        ),
    ]
