# Generated by Django 4.2.7 on 2026-01-17 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_loanapplication_disbursed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='core.agent')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('agent', 'employee')},
            },
        ),
    ]
