# Generated by Django 4.2.7 on 2026-02-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_subadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAdmin',
        ),
    ]
