# Generated by Django 4.2.7 on 2026-02-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_subadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('subadmin', 'SubAdmin'), ('dsa', 'DSA'), ('employee', 'Employee'), ('agent', 'Agent')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='SubAdminEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('applicant_phone', models.CharField(max_length=15)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_type', models.CharField(choices=[('Personal Loan', 'Personal Loan'), ('Business Loan', 'Business Loan'), ('Home Loan', 'Home Loan'), ('Education Loan', 'Education Loan'), ('Auto Loan', 'Auto Loan')], default='Personal Loan', max_length=50)),
                ('loan_tenure', models.IntegerField(help_text='Loan tenure in months')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('New Entry', 'New Entry'), ('Waiting for Processing', 'Waiting for Processing'), ('Required Follow-up', 'Required Follow-up'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='New Entry', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subadmin', models.ForeignKey(limit_choices_to={'role': 'subadmin'}, on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subadmin_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subadmin', '-created_at'], name='subadmin_en_subadmi_e84802_idx'), models.Index(fields=['status'], name='subadmin_en_status_a39d33_idx')],
            },
        ),
    ]
