# Generated by Django 4.2.7 on 2026-02-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_role_subadminentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Required Follow-up'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('disbursed', 'Disbursed'), ('forclose', 'For Close')], default='new_entry', max_length=20),
        ),
    ]
