# Generated by Django 4.2.7 on 2026-03-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_loan_status_alter_loanapplication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Banking Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('disbursed', 'Disbursed'), ('forclose', 'For Close')], default='new_entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('New Entry', 'New Entry'), ('Waiting for Processing', 'Waiting for Processing'), ('Required Follow-up', 'Banking Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='New Entry', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Banking Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanstatushistory',
            name='to_status',
            field=models.CharField(choices=[('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Banking Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subadminentry',
            name='status',
            field=models.CharField(choices=[('New Entry', 'New Entry'), ('Waiting for Processing', 'Waiting for Processing'), ('Required Follow-up', 'Banking Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='New Entry', max_length=50),
        ),
    ]
