# Generated by Django 4.2.7 on 2026-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_loan_status_alter_loanapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_sm_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='sm_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='sm_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='sm_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='sm_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_sm_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sm_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sm_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sm_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sm_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
