# Generated by Django 4.2.7 on 2026-03-21 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_loan_is_sm_signed_loan_sm_email_loan_sm_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_onboarding_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='other', max_length=50)),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_onboarding_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
