# Generated by Django 4.2.7 on 2026-03-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_agent_created_by_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='created_by_employee',
        ),
    ]
