# Generated by Django 4.2.7 on 2026-03-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_agent_created_by_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(choices=[('pan_card', 'PAN Card'), ('aadhaar_card', 'Aadhaar Card'), ('applicant_photo', 'Applicant Photo'), ('permanent_address_proof', 'Permanent Address Proof'), ('current_address_proof', 'Current Address Proof'), ('salary_slip', 'Salary Slip'), ('bank_statement', 'Bank Statement'), ('form_16', 'Form 16'), ('service_book', 'Service Book'), ('property_documents', 'Property Documents'), ('soa_existing_loan', 'SOA of Existing Loan Account'), ('forclosure_document', 'Forcloser Document'), ('co_applicant_pan', 'Co-applicant PAN'), ('co_applicant_aadhaar', 'Co-applicant Aadhaar'), ('co_applicant_photo', 'Co-applicant Photo'), ('guarantor_pan', 'Guarantor PAN'), ('guarantor_aadhaar', 'Guarantor Aadhaar'), ('guarantor_address_proof', 'Guarantor Address Proof'), ('other', 'Other')], max_length=50),
        ),
    ]
