# Generated by Django 4.2.7 on 2026-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_loandocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('subadmin', 'Partner'), ('dsa', 'DSA'), ('employee', 'Employee'), ('agent', 'Channel Partner')], default='employee', max_length=20),
        ),
    ]
