# Generated by Django 4.2.7 on 2026-04-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_applicant_professional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='document_type',
            field=models.CharField(choices=[('photo', 'Applicant Photo'), ('pan_front', 'PAN Card Front'), ('pan_back', 'PAN Card Back'), ('aadhaar_front', 'Aadhaar Front'), ('aadhaar_back', 'Aadhaar Back'), ('permanent_address', 'Permanent Address Proof'), ('current_address', 'Current Address Proof'), ('salary_slip', 'Salary Slip'), ('bank_statement', 'Bank Statement'), ('form_16', 'Form 16'), ('service_book', 'Service Book'), ('resume', 'Resume')], max_length=50),
        ),
    ]
