# Generated by Django 4.2.7 on 2026-05-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_applicantdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='under_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
