# Generated by Django 4.2.7 on 2026-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_agent_under_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_card_doc',
            field=models.FileField(blank=True, help_text='Upload Aadhar', null=True, upload_to='user_docs/aadhar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_details_doc',
            field=models.FileField(blank=True, help_text='Upload Passbook/Cancel Cheque/Statement', null=True, upload_to='user_docs/bank/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card_doc',
            field=models.FileField(blank=True, help_text='Upload PAN', null=True, upload_to='user_docs/pan/'),
        ),
    ]
