# Generated by Django 4.2.7 on 2026-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_user_aadhar_card_doc_user_bank_details_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal Loan'), ('lap', 'LAP (Loan Against Property)'), ('home', 'Home Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('car', 'Auto Loan'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('lap', 'LAP (Loan Against Property)'), ('home', 'Home Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('car', 'Auto Loan'), ('other', 'Other')], max_length=50),
        ),
    ]
