# Generated by Django 4.2.7 on 2026-06-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_applicant_loan_type_alter_loan_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('loan_added', 'New Loan Added'), ('status_updated', 'Status Updated'), ('agent_registered', 'New Channel Partner Registered'), ('complaint_raised', 'Complaint Raised'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_disbursed', 'Loan Disbursed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(blank=True, help_text='Manual Channel Partner ID', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('agent', 'Channel Partner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='applicant_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('agent', 'Channel Partner')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Bank Login Process'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('disbursed', 'Disbursed'), ('forclose', 'For Close')], default='new_entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('New Entry', 'New Entry'), ('Waiting for Processing', 'Waiting for Processing'), ('Required Follow-up', 'Bank Login Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='New Entry', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Bank Login Process'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanstatushistory',
            name='to_status',
            field=models.CharField(choices=[('new_entry', 'New Entry'), ('waiting', 'Waiting for Processing'), ('follow_up', 'Bank Login Process'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subadminentry',
            name='status',
            field=models.CharField(choices=[('New Entry', 'New Entry'), ('Waiting for Processing', 'Waiting for Processing'), ('Required Follow-up', 'Bank Login Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='New Entry', max_length=50),
        ),
    ]
