# Generated by Django 4.2.7 on 2026-06-09 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_activitylog_action_alter_agent_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocument',
            name='document_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='lead_received_by',
            field=models.ForeignKey(blank=True, help_text='Upper-level lead receiver selected at application creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_received_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='document_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
