# Generated by Django 4.2.7 on 2026-06-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_loan_helpers_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
